# Generated by Django 2.0.3 on 2021-03-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetmodel',
            name='age',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AlterField(
            model_name='tweetmodel',
            name='time',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AlterField(
            model_name='tweetmodel',
            name='transport',
            field=models.CharField(default='0', max_length=500),
        ),
    ]
